### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by kernelsmith** [wjpremerlani/rocket_repo#1]
Bill, this is Josh. I created this issue just so you have my github handle. Feel free to close this ;)

**Comment by wjpremerlani** [comment]
Josh. Thanks. It is a pleasure meeting you. By the way, I did not receive any sort of notification from github that an issue was created. Was that supposed to happen?

**Comment by wjpremerlani** [comment]
Josh. I take back what I said in my last comment. I did get a notification from github, I did not realize you sent it during the zoom meeting, I was not watching my email.

**Comment by kernelsmith** [comment]
Yeah, email's the only notification you'll generally get, tho there are a lot of integrations one can use to monitor/get notified of issues, but I don't personally have any running. I'm going to close this issue so it won't show up as annoyingly to you, but to find it or similar in the future, you can to your issues tab https://github.com/wjpremerlani/rocket_repo/issues and in the filter field you'll see `is:issue is:open` just change that to `is:issue is:closed` and you'll see it. You can also add on a search term like `is:issue is:closed searchterm`
